### ISSUE TITLE
Replace multirust with rustup

### ISSUE THREAD

**Issue by johnjelinek** [esphen/wsta#10]
https://www.rustup.rs is the official replacement for multirust.

**Comment by eliihen** [comment]
Well, technically rustup.rs is still in beta, but seeing as I use it myself at this point and it is seemingly stable, I'll update the README with rustup instructions as you suggest.

**Comment by johnjelinek** [comment]
Well, can yup also update the `brew` formula w/ rustup too?

**Comment by eliihen** [comment]
Will do when I have time

**Comment by eliihen** [comment]
I have now updated the README and the Homebrew formula to no longer use `multirust`. Fun fact - there was no need to use `rustup.rs` in the formula as there is a cask that provides the rust binaries.

Holler if you run into any issues with the new formula
