### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ohall** [esphen/wsta#21]
This tool is a life saver!  Great work.  
My team and I really appreciate the care and effort you put into building and maintaining this.  
Keep up the awesome work.

Thank you!

**Comment by eliihen** [comment]
How nice of you, thanks! I'm glad it helps you and your team.

I'll give you an update on what is going on with the project. I have been prioritizing other projects over wsta for a while, so unfortunately it's fallen a bit behind its dependencies. Trying to update them is a huge endeavor at this point, so I am contemplating rewriting the entire thing. The code base is not that big, so it's comparable to upgrading the dependencies at this point., which requires large changes of their own. 

If the webextension websocket-monitor rewrite doesn't ambush me at some point, then I may be able to work on wsta after the RESTED 2.2.0 release.
