### ISSUE TITLE
install stuck at 'cargo build'

### ISSUE THREAD

**Issue by bupojung** [esphen/wsta#23]
brew install wsta 
stuck at 'cargo build --release' forever.
How to fixed?

MacOS High Sierra 10.13.4

**Comment by eliihen** [comment]
Hi,

I'm not focusing on wsta anymore. Feel free to try and fix this issue and create a PR if you like.

My focus has been on making a more modern replacement for wsta called wurl, you can check that out if you want.

https://github.com/getwurl/wurl

**Comment by bupojung** [comment]
Thanks for you response. I will try Wurl instead.
