### ISSUE TITLE
Homebrew installation fails

### ISSUE THREAD

**Issue by oyvindwe** [esphen/wsta#6]
`$ brew install wsta
==> Installing wsta from esphen/wsta
==> Downloading https://github.com/esphen/wsta/archive/0.2.1.tar.gz
==> Downloading from https://codeload.github.com/esphen/wsta/tar.gz/0.2.1
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: 7923e9bd8310b5a72d8390324bd5150615d0e587ec793f808e12cddbb03e238f
Actual: 48c2c1a73cab9955df0c2cb494d536e904dafa19a7c8ac7c6dac64ae2cb6240a
Archive: /Library/Caches/Homebrew/wsta-0.2.1.tar.gz
To retry an incomplete download, remove the file above.`

Yes, I did delete the file and try again with the same result.

**Comment by eliihen** [comment]
Thanks for reporting.

Yeah, my bad. I re-tagged `0.2.1` today to get new binaries through `rust-everywhere` (see #3) and forgot to update the sha sum. Oops!

I just pushed a new homebrew tap. Please retry and verify if it works

**Comment by oyvindwe** [comment]
I worked around the issue by manually `/usr/local/Library/Taps/esphen/homebrew-wsta/HomebrewFormula/wsta.rb` with the expected hash.

I can confirm you have fixed the issue as well. I did:

```
brew remove wsta
brew untap esphen/wsta
brew tap esphen/wsta https://github.com/esphen/wsta.git
brew install wsta`
```

--> successfully installed

**Comment by eliihen** [comment]
Thanks for the confirmation!
