### ISSUE TITLE
Windows Binaries

### ISSUE THREAD

**Issue by johnjelinek** [esphen/wsta#9]
I've got this running on Windows 10 pretty smoothly. Would you like some binaries to distribute?

**Comment by eliihen** [comment]
Good to hear you got it running! Sure, if you would like to send me some binaries, you will find my email [here](https://henriksen.is).

Also, if the compile instructions for Windows vary from the instructions in the README, I would also merge a PR with updated instructions.

Eventually I want to get [appveyor](http://www.appveyor.com/) to compile binaries for Windows

**Comment by eliihen** [comment]
Windows binaries are now distributed with the new 0.4.0!

https://github.com/esphen/wsta/releases
